name: "Auto-merge Dependabot PRs"

on:
  pull_request:
    paths-ignore:
      - "**/*.md"
  workflow_dispatch:

jobs:
  auto-merge:
    name: "Auto-merge Dependabot PRs"
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.GITHUB_TOKEN }}
