name: Build Amethyst

on: [push, workflow_dispatch, pull_request]

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.6

      - name: Install dependencies
        run: npm i

      - name: Build Amethyst
        run: npm run package

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Amethyst Build Windows
          path: | 
            release/build/*.yml
            release/build/*.exe*

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.6

      - name: Install gcc dependencies
        run: sudo apt install gcc-multilib g++-multilib libvips

      - name: Install dependencies
        run: npm i

      - name: Build Amethyst
        run: npm run package

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Amethyst Build Linux
          path: | 
            release/build/*.yml
            release/build/*.AppImage*



# https://bittu.eu.org/docs/wr-intro/

# name: Publish to WinGet
# on:
#   release:
#     types: [released]
# jobs:
#   publish:
#     runs-on: windows-latest # action can only be run on windows
#     steps:
#       - uses: vedantmgoyal2009/vedantmgoyal2009/winget-pkgs-automation/releaser-action@v1.0.0
#         with:
#           identifier: Package.Identifier
#           version-regex: '[0-9.]+'
#           installers-regex: '\.exe$' # only .exe files
#           delete-previous-version: 'false' # don't forget the quotes
#           token: ${{ secrets.WINGET_TOKEN }}