name: Build Amethyst

on: [push, workflow_dispatch, pull_request]

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.6

      - name: Install dependencies
        run: npm i

      - name: Build Amethyst
        run: npm run package

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Amethyst Linux
          path: release/build/Amethyst-*

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.6

      - name: Install dependencies
        run: npm i

      - name: Build Amethyst
        run: npm run package

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Amethyst Linux
          path: release/build/Amethyst-*