name: Build Amethyst

on:
  push:
    paths-ignore:
      - "**/*.md"
  pull_request_target:
  workflow_dispatch:

jobs:
  lint:
    name: Check for lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.10.0

      - name: Install gcc dependencies
        run: sudo apt install gcc-multilib g++-multilib libvips

      - name: Install Dependencies
        run: npm ci

      - name: Run eslint
        run: npx eslint

  tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.10.0

      - name: Install gcc dependencies
        run: sudo apt install gcc-multilib g++-multilib libvips

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.10.0

      - name: Install Dependencies
        run: npm ci

      - name: Build Amethyst
        run: yarn package

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            release/build/*.yml
            release/build/*.exe*

  build-macos:
    name: Build MacOS
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.10.0

      - name: Install Dependencies
        run: npm ci

      - name: Build Amethyst
        run: USE_HARD_LINKS=false yarn package

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            release/build/*.yml
            release/build/*.dmg
            release/build/*.dmg.*
            release/build/*.zip
            release/build/*.zip.*

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.10.0

      - name: Install gcc dependencies
        run: sudo apt install gcc-multilib g++-multilib libvips

      - name: Install Dependencies
        run: npm ci

      - name: Build Amethyst
        run: yarn package

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            release/build/*.yml
            release/build/*.AppImage*

  publish-releases:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [tests, build-linux, build-windows, build-macos]
    name: Publish Releases
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifact

      - name: Post Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./*"
