name: Build Amethyst

on:
  push:
    paths-ignore:
      - "**/*.md"

jobs:
  lint:
    name: Check for lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: 20.0.0
          cache: 'yarn'

      - name: Install gcc dependencies
        run: sudo apt update && sudo apt install gcc-multilib g++-multilib libvips

      - name: Install Dependencies
        run: yarn install

      - name: Run eslint
        run: yarn lint

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: 20.0.0
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Build Amethyst
        run: yarn package

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifact-windows
          path: |
            release/build/*.yml
            release/build/*.yaml
            release/build/*.exe*

  build-macos:
    name: Build MacOS
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: 20.0.0
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Build Amethyst
        run: USE_HARD_LINKS=false yarn package

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifact-macos
          path: |
            release/build/*.yml
            release/build/*.dmg
            release/build/*.dmg.*
            release/build/*.zip
            release/build/*.zip.*

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: 20.0.0
          cache: 'yarn'

      - name: Install linux dependencies
        run: sudo apt update && sudo apt install rpm snapd libarchive-tools && sudo snap install snapcraft --classic && sudo snap install multipass --beta --classic

      - name: Install Dependencies
        run: yarn install

      - name: Build Amethyst
        run: yarn package

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifact-linux
          path: |
            release/build/*.yml
            release/build/*.yaml
            release/build/*.AppImage
            release/build/*.rpm
            release/build/*.deb
            release/build/*.pacman
            release/build/*.snap

  publish-releases:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build-windows, build-macos, build-linux]
    name: Publish Releases
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: artifact
          merge-multiple: true

      - name: Post Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*"
