name: Build Amethyst

on: [push, workflow_dispatch, pull_request_target]

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.10.0

      - name: Install dependencies
        run: npm i

      - name: Build Amethyst
        run: npm run package

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            release/build/*.yml
            release/build/*.exe*

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.10.0

      - name: Install gcc dependencies
        run: sudo apt install gcc-multilib g++-multilib libvips

      - name: Install dependencies
        run: npm i

      - name: Build Amethyst
        run: npm run package

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            release/build/*.yml
            release/build/*.AppImage*

  publish-releases:
    needs: [build-linux, build-windows]
    if: startsWith(github.ref, 'refs/tags/v')
    name: Publish Releases
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Post Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.yml,*.exe*,*.AppImage*"
