name: Build Amethyst

on: [push, workflow_dispatch, pull_request]

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.6

      - name: Install dependencies
        run: npm i

      - name: Build Amethyst
        run: npm run package

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.6

      - name: Install Snap
        run: sudo apt install snapd

      - name: Install Snap Core
        run: sudo snap install core

      - name: Install snapcraft
        run: sudo snap install snapcraft --classic

      - name: Install dependencies
        run: npm i

      - name: Build Amethyst
        run: npm run package

  build-macos:
    name: Build MacOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.6

      - name: Install dependencies
        run: npm i

      - name: Build Amethyst
        run: npm run package
