
# https://bittu.eu.org/docs/wr-intro/

# name: Publish to WinGet
# on:
#   release:
#     types: [released]
# jobs:
#   publish:
#     runs-on: windows-latest # action can only be run on windows
#     steps:
#       - uses: vedantmgoyal2009/vedantmgoyal2009/winget-pkgs-automation/releaser-action@v1.0.0
#         with:
#           identifier: Package.Identifier
#           version-regex: '[0-9.]+'
#           installers-regex: '\.exe$' # only .exe files
#           delete-previous-version: 'false' # don't forget the quotes
#           token: ${{ secrets.WINGET_TOKEN }}